---
- hosts: frontend
  vars:
    http_port: 80
    max_clients: 200
  remote_user: vagrant
  become: true
  tasks:
  - name: Update Http to latest version
    package:
      name: httpd
      state: present
    notify: restart server
  - name: Update apache config
    template:
      src: templates/httpd.conf.j2
      dest: /etc/httpd/conf/httpd.conf
    when: ansible_facts['os_family'] == "Windows"
    notify: restart server
  - name: Start httpd service
    service:
      name: httpd
      state: started
      enabled: yes
    notify: restart server
  handlers:
    - name: restart server
      command: 'shutdown -r -t sec 1'
  


